version: "3"
services:
    website:
        image: nourimeals/website
        container_name: website
        stdin_open: true
        ports:
          - "8080:8080"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./:/app
